### ISSUE TITLE
Running from Command Palette fails

### ISSUE THREAD

**Issue by ItsOkayItsOfficial** [ericadamski/vscode-carbon_now_sh#1]
When running specified command 'Carbon' out of Command Palette VS Code returns the following error:

> Running the contributed command:'carbon.show' failed.

This occurs when Command Palette is called via Ctrl + Shift + P, F1, or directly from Menu Bar.

Carbon-Now-sh:  version 0.0.1
VS Code: version 1.19.2, architecture x64

**Comment by ericadamski** [comment]
I'll take a look into this issue, I'm not super familiar with vs codes extension setup so it may take a while to figure out the cause, thank you for submitting!

**Comment by ericadamski** [comment]
This should be fixed in #7, reopen if there are issue later.
