### ISSUE TITLE
Remove all settings in favor of browser cache

### ISSUE THREAD

**Issue by ericadamski** [ericadamski/vscode-carbon_now_sh#16]
[From Marketplace Question](https://marketplace.visualstudio.com/items?itemName=ericadamski.carbon-now-sh&tracking_data=eyJTb3VyY2UiOiJFbWFpbCIsIlR5cGUiOiJOb3RpZmljYXRpb24iLCJTSUQiOiJtcy5HYWxsZXJ5Tm90aWZpY2F0aW9ucy5xbmEtdXBkYXRlZC1zdWJzY3JpcHRpb24iLCJTVHlwZSI6IkNPTiIsIlJlY2lwIjoxLCJFbGVtZW50IjoiaGVyby9jdGEifQ%3D%3D#qna)
Hey Eric - Just wanted to let you know that you can modify your extension to be MUCH simpler now by removing all the config settings except the url.

The reason is that I pushed a fix to the carbon code base awhile back that is now live. It keeps your last settings when you only pass the ?code=XXX parameter.

https://github.com/dawnlabs/carbon/pull/322

So, rather than have to keep up with the updates that Carbon releases with new themes, settings, etc., all your extension has to do is pass ?code=XXX and nothing else to the carbon URL and you're golden!

---

Thoughts? 💬

**Comment by ericadamski** [comment]
I hesitate to remove all settings for people who have either never been to carbon.now.sh before, or those who want to attempt to mimic their editor settings.

But it would be a nice option to say ignore all of these settings in favor of the cached version on the browser.

Removing the settings feels way to intrusive to other people who have become accustomed to using them.

**Comment by mittalyashu** [comment]
Add all the settings of Carbon inside VS Code

![image](https://user-images.githubusercontent.com/29014463/42691718-cc393a10-86c6-11e8-99d4-3759430f57fc.png)

**Comment by stevensacks** [comment]
What @mittalyashu said reinforces my point. @ericadamski, unless you want to constantly keep your plugin up-to-date with all the additions/improvements that carbon.now.sh makes to their platform, you're better off letting users use their settings on carbon itself and free yourself of the need to continually update this extension (you're already pretty far behind, feature set-wise).

To be honest, I choose a different theme in VS Code than I use on carbon.now.sh.

At the very least, please add an option to disable all options and just pass the `code` param to carbon.now.sh. But, I think you'd be well-served to just remove all the options entirely. Sometimes, a simple extension that does exactly what it's supposed to do and nothing more is all you really need. :)

**Comment by ericadamski** [comment]
Setting to use browser cache added in #17 :)
