### ISSUE TITLE
"Cardon" command open file explorer

### ISSUE THREAD

**Issue by Hartaxfr** [ericadamski/vscode-carbon_now_sh#5]
When using "carbon" command, it open my file explorer :/

![qsdqsdqsdd](https://user-images.githubusercontent.com/3418195/35865453-d64a0a40-0b54-11e8-8faf-f9ba5ce4964e.gif)

**Comment by ericadamski** [comment]
Windows support should be good now thanks to https://github.com/ericadamski/vscode-carbon_now_sh/commit/b1fc5eaa24a2804164f24ed7d348682cf3cf1b2d

**Comment by Hartaxfr** [comment]
It works ;)
Just sad not to have selected text in vsc with auto insert in carbon website :(

**Comment by ericadamski** [comment]
@Hartaxfr  it is in the roadmap! See issue #4, I hope to get this out soon as it is already supported on Atom
