### ISSUE TITLE
Error & Can't Debug

### ISSUE THREAD

**Issue by Apidcloud** [ericadamski/vscode-carbon_now_sh#8]
Good afternoon!

I've installed the extension, but running 'Carbon' from the command palette raises the following error:

> There was an issue sending code to carbon. Please try again.

I'm trying to take a look at the code, so I cloned the repo. But F5 doesn't seem to be taking any effect.
![image](https://user-images.githubusercontent.com/3720818/36320698-f00a4016-133e-11e8-99a8-7b4879b04944.png)

Is there anything else I should do in order to debug it?

thanks!

Edit: I'll try the `yo generator` code with a simple example to check if it's a problem with the launch.json or something.

Edit 2: Yeah, for some reason the pretask doesn't work correctly. running `npm run watch` manually does the trick. I'll now take a look at the issue I first mentioned.

**Comment by Apidcloud** [comment]
Removing every search param, other than `code` seems to work though.

Seems to be an issue with openurl2:

   

>  throw err;
>     ^
> 
> Error: Cannot find module 'C:\Program Files\Microsoft VS Code\=erewrew'
>     at Function.Module._resolveFilename (module.js:470:15)
>     at Function.Module._load (module.js:418:25)
>     at Module.runMain (module.js:605:10)
>     at run (bootstrap_node.js:431:7)
>     at startup (bootstrap_node.js:155:9)
>     at bootstrap_node.js:551:3
> 	at Socket.<anonymous> (D:\Workspace\Github\vscode-carbon_now_sh\node_modules\openurl2\openurl.js:33:25)
> 	at emitNone (events.js:91:20)
> 	at Socket.emit (events.js:188:7)
> 	at endReadableNT (_stream_readable.js:975:12)
> 	at _combinedTickCallback (internal/process/next_tick.js:80:11)
> 	at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by ericadamski** [comment]
@Apidcloud Thank you so much for all this work! I will test it on my mac and merge it if all its well :) ❤️

**Comment by Apidcloud** [comment]
You’re welcome!

I created a PR in openurl2 that fixes the underlying issue. It it gets merged and published, you can just update the package version here :)


On 16 Feb 2018, at 19:45, Eric Adamski <notifications@github.com<mailto:notifications@github.com>> wrote:


Reopened #8<https://github.com/ericadamski/vscode-carbon_now_sh/issues/8>.

**Comment by ericadamski** [comment]
Ya, I will keep an eye on it :D Thank you again!

**Comment by ericadamski** [comment]
It's not yet, I was waiting for the package that is used to merge a PR that would fix it but I will take a stab at it myself until the package gets fixed!

Could you attached the code you tried to send, maybe it's a different problem.

Thank you for commenting ❤️ @sss63232

**Comment by ericadamski** [comment]
@sss63232 @Apidcloud I do not have a windows machine, is the problem the `&` in the URL or in the code block attempting to be sent?

**Comment by ericadamski** [comment]
@sss63232 @Apidcloud Since there was no response on the PR required for this issue, I forked the repo and released it under the package name [`opn-url`](https://github.com/ericadamski/opn-url) [npm](https://www.npmjs.com/package/opn-url) and applied the fix myself.

If one of you could give it a whirl and let me know if it is fixed otherwise lets try and get some more details on the error with the better debugging

**Comment by Apidcloud** [comment]
Oh, I was going to suggest that. Did you test the changes? I know it works for windows, but I'm not sure if the change can be applied to other OSSs.

I'll give it a go and let you know!

**Comment by Apidcloud** [comment]
Yeah, it seems to work just fine 😄 

@sss63232 Can you try to install the extension again? It should work under Windows now.

**Comment by ericadamski** [comment]
@Apidcloud works ok for me on MacOS!

**Comment by ericadamski** [comment]
I am going to go ahead and close this issue, if you happen to have this error again please re-open! 

Thanks for the help❤️
