### ISSUE TITLE
Running in codebase with string formating fails

### ISSUE THREAD

**Issue by gangachris** [ericadamski/vscode-carbon_now_sh#9]
I've tested with a code snippet that contains `%f` for formatting floating point numbers and I get back an internal server error. It looks like a URL parsing issue, since because of the `%`

**Comment by ericadamski** [comment]
Thanks for taking a look! I can take a look later today ❤️

**Comment by ericadamski** [comment]
@gangachris 

This may be the solution [`encodeURIComponent`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent)

I have been using `encodeURI` but it may not be doing a good enough job on the code.

**Comment by gangachris** [comment]
Did a local test with `encodeURIComponent` and it seemed to work. Here's a fix #10. My question though is whether to do the same encoding for every other url search param.

**Comment by ericadamski** [comment]
I took a look here https://github.com/dawnlabs/carbon/blob/a6324586eb8313cf5283b2ab5f04491e08ca6206/lib/routing.js#L88-L98

It seems they use `encodeURI` for the entire url and here https://github.com/dawnlabs/carbon/blob/a6324586eb8313cf5283b2ab5f04491e08ca6206/lib/routing.js#L101-L103

they use `encodeURIComponent` for the code.

So it should be ok

**Comment by ericadamski** [comment]
@gangachris thank you for this PR (#10)!
